jobs:
  deploy-to-first-host:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            #cd /var/www/u1538455/data/www/site100.ru/projects/form-span-defender
            #git clone git@github.com:site100ru/form-span-defender.git .
            
            #cd /var/www/u1538455/data/www/site100.ru/projects/form-span-defender
            #git pull
